#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx-role
- name: Force apt package cache update
  apt:
    update_cache: yes
    force_apt_get: yes   # Forces raw system apt execution stability
  tags: [always]
  
- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Deploy Webpage
  copy:
    src: index.html
    dest: /var/www/html/index.html